name: spidersense
description: "Spider-Sense: Assistant for the visually impaired using Edge AI."
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Navigation
  get: ^4.6.6

  # Backend & Authentication (Supabase)
  supabase_flutter: ^2.0.2

  # AI & Vision (Offline)
  camera: ^0.10.5+5
  tflite_v2: 1.0.0
  flutter_tts: ^3.8.5

  # Storage & Connectivity
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2

  # UI & Design
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/langs/en-US.json
    - assets/langs/es-ES.json
    - assets/models/