class ObjectLabels {
  static const Map<String, String> translations = {
    'person': 'Persona',
    'bicycle': 'Bicicleta',
    'car': 'Automóvil',
    'motorcycle': 'Motocicleta',
    'airplane': 'Avión',
    'bus': 'Bus',
    'train': 'Tren',
    'truck': 'Camión',
    'boat': 'Bote',
    'traffic light': 'Semáforo',
    'fire hydrant': 'Hidrante',
    'stop sign': 'Señal de pare',
    'parking meter': 'Parquímetro',
    'bench': 'Banco',
    'bird': 'Pájaro',
    'cat': 'Gato',
    'dog': 'Perro',
    'horse': 'Caballo',
    'sheep': 'Oveja',
    'cow': 'Vaca',
    'elephant': 'Elefante',
    'bear': 'Oso',
    'zebra': 'Cebra',
    'giraffe': 'Jirafa',
    'backpack': 'Mochila',
    'umbrella': 'Paraguas',
    'handbag': 'Bolso',
    'tie': 'Corbata',
    'suitcase': 'Maleta',
    'bottle': 'Botella',
    'wine glass': 'Copa',
    'cup': 'Taza',
    'fork': 'Tenedor',
    'knife': 'Cuchillo',
    'spoon': 'Cuchara',
    'bowl': 'Tazón',
    'banana': 'Banano',
    'apple': 'Manzana',
    'sandwich': 'Sándwich',
    'orange': 'Naranja',
    'broccoli': 'Brócoli',
    'carrot': 'Zanahoria',
    'hot dog': 'Perro caliente',
    'pizza': 'Pizza',
    'donut': 'Dona',
    'cake': 'Torta',
    'chair': 'Silla',
    'couch': 'Sofá',
    'potted plant': 'Planta',
    'bed': 'Cama',
    'dining table': 'Mesa',
    'toilet': 'Inodoro',
    'tv': 'Televisor',
    'laptop': 'Portátil',
    'mouse': 'Ratón',
    'remote': 'Control remoto',
    'keyboard': 'Teclado',
    'cell phone': 'Celular',
    'microwave': 'Microondas',
    'oven': 'Horno',
    'toaster': 'Tostadora',
    'sink': 'Lavamanos',
    'refrigerator': 'Nevera',
    'book': 'Libro',
    'clock': 'Reloj',
    'vase': 'Florero',
    'scissors': 'Tijeras',
    'teddy bear': 'Oso de peluche',
    'hair drier': 'Secador',
    'toothbrush': 'Cepillo de dientes',
  };

  static const List<String> dangerousObjects = [
    'car',
    'truck',
    'bus',
    'motorcycle',
    'bicycle',
    'dog',
    'cat',
    'person',
    'train',
    'traffic light',
    'stop sign',
    'fire hydrant',
  ];

  static String translate(String label) =>
      translations[label.toLowerCase()] ?? label;

  static bool isDangerous(String label) =>
      dangerousObjects.contains(label.toLowerCase());
}